AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda Functions for the Default Use Case. 

Parameters:  
  ConversationRelayDynamoDBUtilLayerVersion:
    Type: String
    Default: '1'    
  ConversationRelaySaveToolCallResultLayerVersion:
    Type: String
    Default: '1'    

Globals:
  Function:
    Timeout: 35

Resources:

  ##########################################################################
  #  (DefaultSaveFirstAndLastName) Lambda Function                            
  ##########################################################################
  DefaultSaveFirstAndLastName:
    Type: AWS::Serverless::Function
    Properties:      
      FunctionName: DefaultSaveFirstAndLastName
      Description: Function to save a user's first and last name.
      CodeUri: lambdas/default-save-name-function/
      AutoPublishAlias: live
      Handler: app.lambdaHandler
      Runtime: nodejs20.x      
      Architectures:
        - arm64
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: !ImportValue  CRPrimaryDynamoTableName                           
      Policies:        
        - DynamoDBCrudPolicy:
            TableName: !ImportValue  CRPrimaryDynamoTableName
      Layers:
        -
          !Sub 
          - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:ConversationRelaySaveToolCallResultLayer:${cv}'
          - cv : !Ref 'ConversationRelaySaveToolCallResultLayerVersion'
  
##########################################################################
  #  (DefaultSaveUseCase) Lambda Function                            
  ##########################################################################
  DefaultSaveUseCase:
    Type: AWS::Serverless::Function
    Properties:      
      FunctionName: DefaultSaveUseCase
      Description: Sample function that returns a movice character.
      CodeUri: lambdas/default-save-use-case/
      AutoPublishAlias: live
      Handler: app.lambdaHandler
      Runtime: nodejs20.x      
      Architectures:
        - arm64     
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: !ImportValue  CRPrimaryDynamoTableName 
      Policies:        
        - DynamoDBCrudPolicy:
            TableName: !ImportValue  CRPrimaryDynamoTableName
      Layers:
        -
          !Sub 
          - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:ConversationRelayDynamoDBUtilLayer:${cv}'
          - cv : !Ref 'ConversationRelayDynamoDBUtilLayerVersion'  
        -
          !Sub 
          - 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:ConversationRelaySaveToolCallResultLayer:${cv}'
          - cv : !Ref 'ConversationRelaySaveToolCallResultLayerVersion'                                                                   